### PR TITLE
Speed up training and inference; fix #18

### LINKED ISSUE #18: Error when executing test.py which is similar to the error #17
The code is latest.
The problem description and exception infomation are same as the issue [#17](https://github.com/amoudgl/pygoturn/issues/17). 
However, the code worked finely when using the pretrained model file which was downloaded from Google Drive. So, I am thinking that whether the number of batch is too small when training the model manually.
P.S. My `num_batch` is 50 when training the model manually by executing the command `python train.py`.

### PR DESCRIPTION
**Pull request by amoudgl**
Updates: 

- [x] Remove PIL, matplotlib and skimage packages, use opencv. 
- [x] Inference runs at 200+ fps. 
- [x] 5x speedup in training. 
- [x] Fix crop methodology to handle invalid regression outputs (#18). 
- [x] PyTorch latest updates - remove `Variable()` and use `torch.device`. 
- [x] Fix opencv visualization of batch in dataset classes.
- [x] Fix demo script.
- [x] Reproduce GOTURN results on OTB. 
- [x] Update README. 
~~Update notebook for batch visualization.~~ (skipped in this pull request)

### CODE REVIEW

**Comment by fzh0917** [comment]
When do you expect to complete this branch and merge it to the master branch?

**Comment by amoudgl** [comment]
I'm a bit busy with other work commitments but I hope to get this done by the end of this week. :)

**Comment by fzh0917** [comment]
OK, thanks. I am looking forward to seeing the new version.

**Comment by amoudgl** [comment]
@fzh0917 I have merged this PR, check out the new version!

**Pull request merged**
